Numpy

In [2]:
import numpy as np

#dir(np.ndarray)

ls1 = [3, 2, 5, 6, 9999999999]
ls2 = [9, 3, 5, 4, 1]

data1 = np.array(ls1)
data2 = np.array([ls1, ls2])

print(data1, data1.shape, data1.ndim, data1.dtype)
print(data2, data2.shape, data2.ndim, data2.dtype)

data3 = np.asarray(data1)
print(data3, id(data1), id(data3))
data3 = np.asarray(ls1)
print(data3, id(data1), id(data3))

print(f"range :{np.arange(3, 10, 3)}")
print(f"zeros(n) : {np.zeros(4)}")
print(f"zeros((r, c)) : \n {np.zeros((3,2))}")
print(f"zeros_like(obj) : {np.zeros_like(ls1)}")
print(f"zeros_like(ndarray) : \n{np.zeros_like(data2)}")
print(f"eye(n) : \n{np.eye(3)}")
print(f"empty_like(obj) : {np.empty_like(ls1)}")
print(f"empty_like(ndarray) : \n{np.empty_like(data2)}")

[         3          2          5          6 9999999999] (5,) 1 int64
[[         3          2          5          6 9999999999]
 [         9          3          5          4          1]] (2, 5) 2 int64
[         3          2          5          6 9999999999] 1972946685344 1972946685344
[         3          2          5          6 9999999999] 1972946685344 1972950549088
range :[3 6 9]
zeros(n) : [0. 0. 0. 0.]
zeros((r, c)) : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
zeros_like(obj) : [0 0 0 0 0]
zeros_like(ndarray) : 
[[0 0 0 0 0]
 [0 0 0 0 0]]
eye(n) : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
empty_like(obj) : [         3          2          5          6 9999999999]
empty_like(ndarray) : 
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
matrix1 = np.array([[x for x in range(0,5)],[x ** 2 for x in range(0,5)]])
matrix1

array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  4,  9, 16]])

In [4]:
vec_a = np.array(ls1, dtype=np.string_)
print(vec_a)
vec_a2 = vec_a.astype(np.complex128)
vec_a2 + 10

[b'3' b'2' b'5' b'6' b'9999999999']


array([1.3e+01+0.j, 1.2e+01+0.j, 1.5e+01+0.j, 1.6e+01+0.j, 1.0e+10+0.j])

In [5]:
matrix2 = np.random.randn(3,3)
matrix2, matrix2 * np.eye(3)

(array([[-0.94657925, -1.42505749, -0.13619156],
        [-1.90713933,  0.05349584, -0.04305895],
        [-1.85467948,  0.47033821, -1.59311369]]),
 array([[-0.94657925, -0.        , -0.        ],
        [-0.        ,  0.05349584, -0.        ],
        [-0.        ,  0.        , -1.59311369]]))

In [6]:
ls = [2,3,4,5,6,4,3]
x = np.array(ls)

ls[2:5] = [6]
x[2:5] = 6
ls, x

([2, 3, 6, 4, 3], array([2, 3, 6, 6, 6, 4, 3]))

In [7]:
array1 = np.array([
    [2, 6, 8, 7],
    [25, 31, 78, 96],
    [101, 204, 109, 157]
])
array1[2], array1[:2], array1[2][1], array1[2,1], array1[:2, 1:2]

(array([101, 204, 109, 157]), array([[ 2,  6,  8,  7],
        [25, 31, 78, 96]]), 204, 204, array([[ 6],
        [31]]))

In [8]:
ls11 = [1,2,3,4]
ls12 = [5,6,7,8]
ls13 = [9, 10, 11, 12]
ls21 = [13,14,15,16]
ls22 = [17,18,19,20]
ls23 = [21, 22, 23, 24]
matrix3 = np.array([[ls11, ls12, ls13],[ls21, ls22, ls23]])
matrix3, matrix3.shape, matrix3.ndim

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]), (2, 3, 4), 3)

In [9]:
matrix4 = np.array([ls11, ls12])
matrix4, matrix4[matrix4>=4], matrix4[1]

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([4, 5, 6, 7, 8]), array([5, 6, 7, 8]))

In [10]:
name = np.array(["남자", "여자", "남자","남자","남자", "여자"])
score = np.array([ls11, ls12, ls13, ls21, ls22, ls23])
name_bool = name == "여자"
name, score, name_bool

(array(['남자', '여자', '남자', '남자', '남자', '여자'], dtype='<U2'),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([False,  True, False, False, False,  True]))

In [11]:
female = score[name_bool]
male = score[~name_bool]
abc = score[[True,False,False,False,False,(True)]]
female, male, abc

(array([[ 5,  6,  7,  8],
        [21, 22, 23, 24]]), array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]), array([[ 1,  2,  3,  4],
        [21, 22, 23, 24]]))

In [12]:
arr = np.random.randn(7, 4)
arr3 = arr[[5, 0, 2], [1, 0, 2]]
arr4 = arr[[5, 0, 2]][:, [1, 0, 2]]
arr5 = arr[np.ix_([5, 0, 2], [1, 0, 2])]
arr4, arr5

(array([[-0.57628679, -0.37900033,  1.39094199],
        [ 0.38925652,  0.26043803, -1.03376945],
        [-0.63650191,  0.85938276,  0.14349315]]),
 array([[-0.57628679, -0.37900033,  1.39094199],
        [ 0.38925652,  0.26043803, -1.03376945],
        [-0.63650191,  0.85938276,  0.14349315]]))

In [13]:
arr = np.arange(24).reshape(2, 4, 3)
arr, arr.T

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]), array([[[ 0, 12],
         [ 3, 15],
         [ 6, 18],
         [ 9, 21]],
 
        [[ 1, 13],
         [ 4, 16],
         [ 7, 19],
         [10, 22]],
 
        [[ 2, 14],
         [ 5, 17],
         [ 8, 20],
         [11, 23]]]))

In [14]:
arr.transpose(2,1,0)

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [15]:
arr.swapaxes(2,1)

array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

In [16]:
arr.swapaxes(2,0)

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [17]:
arr.swapaxes(0,1), arr.swapaxes(1, 0)

(array([[[ 0,  1,  2],
         [12, 13, 14]],
 
        [[ 3,  4,  5],
         [15, 16, 17]],
 
        [[ 6,  7,  8],
         [18, 19, 20]],
 
        [[ 9, 10, 11],
         [21, 22, 23]]]), array([[[ 0,  1,  2],
         [12, 13, 14]],
 
        [[ 3,  4,  5],
         [15, 16, 17]],
 
        [[ 6,  7,  8],
         [18, 19, 20]],
 
        [[ 9, 10, 11],
         [21, 22, 23]]]))

In [18]:
ex = np.arange(24).reshape(2, 4, 3)
np.array([1.4, 2, np.inf, np.nan])

array([1.4, 2. , inf, nan])

In [19]:
x = np.array([2.5,5.6,8.1,3.9,5.7])
y = np.array([2,6,-3,4,-5])
z = np.array([x,y])

print(f"sqrt = {np.sqrt(x)}")
print(f"rint = {np.rint(np.exp(x))}")
print(f"log = {np.log(x)}")
print(f"abs = {np.abs(y)}")
print(f"sign = {np.sign(y)}")

r, q = np.modf(z)
print(f"modf = {r}\n{q}")

sqrt = [1.58113883 2.36643191 2.84604989 1.97484177 2.38746728]
rint = [  12.  270. 3294.   49.  299.]
log = [0.91629073 1.7227666  2.09186406 1.36097655 1.74046617]
abs = [2 6 3 4 5]
sign = [ 1  1 -1  1 -1]
modf = [[ 0.5  0.6  0.1  0.9  0.7]
 [ 0.   0.  -0.   0.  -0. ]]
[[ 2.  5.  8.  3.  5.]
 [ 2.  6. -3.  4. -5.]]


In [20]:
xarr = np.array([1,2,3,4,5])
yarr = np.array([6,7,8,9,10])
zarr = np.array(["a", "b", "c", "d", "e"])
res = [(x if z == "a" else y) for x, y, z in zip(xarr, yarr, zarr)]
res2 = np.where(zarr=="a", xarr, yarr)
res, res2

([1, 7, 8, 9, 10], array([ 1,  7,  8,  9, 10]))

In [21]:
arr1 = (70 + 30*np.random.randn(12)).reshape(4,3)
arr2 = (10 + 5*np.random.randn(12)).reshape(4,3)
result = np.where(arr1 >= 60, arr2, 0)
arr1, arr2, result

(array([[95.56131283, 64.17440132, 50.35450052],
        [35.60605728, 82.39800815, 84.93411634],
        [73.72047204, 43.11061991, 75.95625892],
        [61.41598221, 77.61807506, 37.31574941]]),
 array([[ 7.30402328,  2.11607144,  8.86803366],
        [19.83022888, 15.33077526,  6.21670813],
        [13.94077937,  1.66514484,  7.1684185 ],
        [16.1096986 , 15.14195804,  5.8777901 ]]),
 array([[ 7.30402328,  2.11607144,  0.        ],
        [ 0.        , 15.33077526,  6.21670813],
        [13.94077937,  0.        ,  7.1684185 ],
        [16.1096986 , 15.14195804,  0.        ]]))

In [22]:
xarr = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
print(xarr.sum(), np.sum(xarr))
print(xarr.mean(), np.mean(xarr))
print(xarr.std(), np.std(xarr))
print(xarr.std(ddof=1), np.std(xarr, ddof=1))
print(xarr.var(), np.var(xarr))
print(xarr.min(), np.min(xarr))
print(xarr.max(), np.max(xarr))
print(xarr.argmin(), np.argmin(xarr))
print(xarr.argmax(), np.argmax(xarr))
print(xarr.cumsum(), np.cumsum(xarr))
print(xarr.cumprod(), np.cumprod(xarr))


25.799999999999997 25.799999999999997
5.159999999999999 5.159999999999999
1.8863721796082553 1.8863721796082553
2.109028212234251 2.109028212234251
3.5584000000000002 3.5584000000000002
2.5 2.5
8.1 8.1
0 0
2 2
[ 2.5  8.1 16.2 20.1 25.8] [ 2.5  8.1 16.2 20.1 25.8]
[2.500000e+00 1.400000e+01 1.134000e+02 4.422600e+02 2.520882e+03] [2.500000e+00 1.400000e+01 1.134000e+02 4.422600e+02 2.520882e+03]


In [23]:
xarr2 = np.array([xarr, xarr, xarr, xarr])
xarr2.mean(axis=0, keepdims=True)

array([[2.5, 5.6, 8.1, 3.9, 5.7]])

In [24]:
np.random.shuffle(xarr2[0])
np.mean(xarr2, axis=1)

array([5.16, 5.16, 5.16, 5.16])

In [25]:
np.sort(xarr2, axis=1)

array([[2.5, 3.9, 5.6, 5.7, 8.1],
       [2.5, 3.9, 5.6, 5.7, 8.1],
       [2.5, 3.9, 5.6, 5.7, 8.1],
       [2.5, 3.9, 5.6, 5.7, 8.1]])

In [26]:
x = np.array([1, 2, 5, 6, 7, 9, 2, 4])
aa = np.array([[8, 2, 6, 7], [5, 6, 7, 9]])
np.save("lecture_data/arr_x.npy", x)
load_x = np.load("lecture_data/arr_x.npy")
print(f"load_x : {load_x}")

np.savez("lecture_data/arr.npz", a=x, b=aa)
load_x_aa = np.load("lecture_data/arr.npz")
print(load_x_aa)
print("load_x_aa['a']\n{0}".format(load_x_aa["a"]))
print(f"load_x_aa['b']\n{load_x_aa['b']}")

load_x : [1 2 5 6 7 9 2 4]
load_x_aa['a']
[1 2 5 6 7 9 2 4]
load_x_aa['b']
[[8 2 6 7]
 [5 6 7 9]]


In [28]:
steel_data = np.loadtxt("lecture_data/steel.txt",
                       skiprows=5,
                       delimiter="\t", 
                       encoding="utf-8")
steel_data

array([[ 81.4, 195. ,  57. ],
       [122.2, 179. ,  61. ],
       [101.7, 205. ,  60. ],
       [175.6, 204. ,  62. ],
       [150.3, 201. ,  61. ],
       [ 64.8, 184. ,  54. ],
       [ 92.1, 210. ,  58. ],
       [113.8, 209. ,  61. ]])

In [31]:
steel_data = np.loadtxt("lecture_data/steel.txt",
                       skiprows=5,
                       delimiter="\t",
                       usecols=(0, 2),
                       unpack=True,
                       encoding="utf-8")
steel_data

array([[ 81.4, 122.2, 101.7, 175.6, 150.3,  64.8,  92.1, 113.8],
       [ 57. ,  61. ,  60. ,  62. ,  61. ,  54. ,  58. ,  61. ]])

In [ ]:
a = np.array([[1, 3, 5, 7],[5, 3, 4, 7]])
b = np.array([[1, 3], [5, 7], [5, 3], [4, 7]])
c = np.array([[4, 9, 1, 3], [7, 5, 2, 7], [5, 3, 4, 3], [1, 4, 7, 9]])
a, b, c

In [ ]:
print(np.dot(a, b))
print(np.diag(c))
print(np.diag(a[1]))
print(np.trace(a))
print(np.linalg.det(c))

In [ ]:
var_a = np.arange(8).reshape(4, 2)
var_b = np.array([[1, 2, 3, 4], [4, 3, 2 ,1]])
var_c = np.array([[1, 1, 1, 1], [2, 2, 2, 20], [3, 3, 3, 3], [4, 5, 5, 4]])
var_a, var_b, var_c
var_c2 = np.linalg.inv(var_c)
np.rint(np.dot(var_c, var_c2))

In [29]:
y = np.array([2, 4, 6, 3, 7, 1])
x = np.array([[1, 2, 3, 7], [1, 5, 7, 6], [1, 6, 7, 3], [1, 7, 3, 4], [1, 8, 4, 3], [1, 3, 2, 5]])
np.linalg.lstsq(x, y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.1991453 ,  0.44871795,  0.45854701, -0.35811966]),
 array([5.52948718]),
 4,
 array([20.5718539 ,  5.90695272,  3.85261955,  0.25309904]))

In [32]:
xt = x.T
xpx = np.dot(xt, x)
np.dot(np.dot(np.linalg.inv(xpx), xt), y)

array([ 1.1991453 ,  0.44871795,  0.45854701, -0.35811966])