Numpy

In [78]:
import numpy as np

steel_data1 = np.loadtxt("lecture_data/steel.txt",
                       skiprows=5,
                       delimiter="\t",
                       usecols=(1, 2),
                       encoding="utf-8")

steel_data2 = np.loadtxt("lecture_data/steel.txt",
                       skiprows=5,
                       delimiter="\t",
                       usecols=0,
                       encoding="utf-8")
steel_data1, steel_data2
steel_data3 = np.ones((steel_data1.shape[0], steel_data1.shape[1]+1))
steel_data3[:,1:] = steel_data1
steel_data3

array([[  1., 195.,  57.],
       [  1., 179.,  61.],
       [  1., 205.,  60.],
       [  1., 204.,  62.],
       [  1., 201.,  61.],
       [  1., 184.,  54.],
       [  1., 210.,  58.],
       [  1., 209.,  61.]])

In [79]:
lstlq1 = np.linalg.lstsq(steel_data3, steel_data2)
lstlq1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01]),
 array([2340.88393765]),
 3,
 array([5.86352311e+02, 8.94176555e+00, 1.09839713e-01]))

In [80]:
np.random.randn(10), np.random.normal(loc=10, scale=2, size=(4, 4))

(array([ 0.76736874,  0.98491984,  0.27083585,  1.39198619,  0.07984231,
        -0.39996458, -1.02785056, -0.58471821,  0.81659393, -0.08194705]),
 array([[ 9.31046797, 11.05657629,  7.86202243,  8.97623738],
        [10.58241072, 11.13306739, 11.00718352, 10.57059137],
        [10.96857623, 12.72696302,  8.43778943,  9.06396467],
        [12.44914871,  7.43778345, 11.75095101,  6.57856935]]))

In [81]:
ls = [[x if x == 1 else y for x in range(1, 5)] for y in range(1, 5)]

Pandas

In [82]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

obj = Series([x for x in range(1, 10, 2)])
print(f"Series : \n{obj}\nvalue \n{obj.values}\nindex \n{obj.index}")

Series : 
0    1
1    3
2    5
3    7
4    9
dtype: int64
value 
[1 3 5 7 9]
index 
RangeIndex(start=0, stop=5, step=1)


In [83]:
obj = Series([x for x in range(1, 10, 2)], index = ["a", "b", "c", "d", "e"])
print(obj)
print(f"Series[['b', 'd']\n{obj[['b', 'd']]}]")

a    1
b    3
c    5
d    7
e    9
dtype: int64
Series[['b', 'd']
b    3
d    7
dtype: int64]


In [84]:
obj1 = obj[(obj >= 3) & (obj <= 7)] + 10
obj1

b    13
c    15
d    17
dtype: int64

In [85]:
dic = {"a" : 1, "b": 2, "c" : 3, "d" : 4}
obj2 = Series(dic)
print(obj2)
obj3 = Series(dic, index=["d", "c", "b", "aa"])
obj3

a    1
b    2
c    3
d    4
dtype: int64


d     4.0
c     3.0
b     2.0
aa    NaN
dtype: float64

In [86]:
print(pd.isnull(obj3))

d     False
c     False
b     False
aa     True
dtype: bool


In [87]:
obj1 = Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
obj2 = Series([5, 6, 7, 8, 9], index=["b", "c", "e", "d", "f"])
obj_sum = obj1 + obj2
print(obj_sum)
obj_sum.name = "Total Score"
obj_sum.index.name = "i"
print(obj_sum)
pd.isnull(obj_sum)

a     NaN
b     7.0
c     9.0
d    12.0
e     NaN
f     NaN
dtype: float64
i
a     NaN
b     7.0
c     9.0
d    12.0
e     NaN
f     NaN
Name: Total Score, dtype: float64


i
a     True
b    False
c    False
d    False
e     True
f     True
Name: Total Score, dtype: bool

In [88]:
data = {"a" : [1, 2], "b" : [3, 4]}
df = DataFrame(data)
df

a  b
0  1  3
1  2  4

In [89]:
df1 = DataFrame(data, columns=["b", "a", "c"])
df1

b  a    c
0  3  1  NaN
1  4  2  NaN

In [90]:
arr = np.array([[10, 25, 32, 42],[85, 75, 96, 45],[68, 78, 94, 83]])
print(arr)
df = DataFrame(arr)
print(df)
df1 = DataFrame(arr, columns=["v1", "v2", "v3", "v4"], index=["a", "b", "c"])
df1

[[10 25 32 42]
 [85 75 96 45]
 [68 78 94 83]]
    0   1   2   3
0  10  25  32  42
1  85  75  96  45
2  68  78  94  83


v1  v2  v3  v4
a  10  25  32  42
b  85  75  96  45
c  68  78  94  83

In [91]:
print(f"행색인{df1.index}")
print(f"열색인{df1.columns}")
print(f"행색인{df1.ix['a']}")
print(f"행색인{df1.loc['b']}")
print(f"행인덱스{df1.iloc[0]}")
print(f"행색인{df1.loc[['b', 'a']]}")
print(f"행인덱스{df1.iloc[[1, 0]]}")
print(f"열색인{df1.v1}")
print(f"열색인{df1['v1']}")

행색인Index(['a', 'b', 'c'], dtype='object')
열색인Index(['v1', 'v2', 'v3', 'v4'], dtype='object')
행색인v1    10
v2    25
v3    32
v4    42
Name: a, dtype: int32
행색인v1    85
v2    75
v3    96
v4    45
Name: b, dtype: int32
행인덱스v1    10
v2    25
v3    32
v4    42
Name: a, dtype: int32
행색인   v1  v2  v3  v4
b  85  75  96  45
a  10  25  32  42
행인덱스   v1  v2  v3  v4
b  85  75  96  45
a  10  25  32  42
열색인a    10
b    85
c    68
Name: v1, dtype: int32
열색인a    10
b    85
c    68
Name: v1, dtype: int32


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


In [92]:
var = Series([10, 9], index=["b", "d"])
print(df1, var)
df1["v5"] = var
print(df1)
print(f"열의 행색인{df1.iloc[[0, 2]].v1}")
df1.iloc[0].v1

   v1  v2  v3  v4
a  10  25  32  42
b  85  75  96  45
c  68  78  94  83 b    10
d     9
dtype: int64
   v1  v2  v3  v4    v5
a  10  25  32  42   NaN
b  85  75  96  45  10.0
c  68  78  94  83   NaN
열의 행색인a    10
c    68
Name: v1, dtype: int32


10.0

In [93]:
obj = Series([2.5, 6.4, 7.8, 6.5], index=["a", "b", "c", "d"])
print(obj)
obj1 = obj.reindex(["e", "d", "c", "b", "a"])
obj1

a    2.5
b    6.4
c    7.8
d    6.5
dtype: float64


e    NaN
d    6.5
c    7.8
b    6.4
a    2.5
dtype: float64

In [94]:
obj2 = obj.reindex(["e", "d", "c", "b", "a"], fill_value=0)
print(obj2)
obj3 = obj2.reindex(["e", "d", "c", "b", "a", "f", "a"], method="ffill" )
obj4 = obj2.reindex(["e", "d", "c", "b", "a", "f", "a"], method="bfill" )
obj3, obj4

e    0.0
d    6.5
c    7.8
b    6.4
a    2.5
dtype: float64


(e    0.0
 d    6.5
 c    7.8
 b    6.4
 a    2.5
 f    NaN
 a    2.5
 dtype: float64, e    0.0
 d    6.5
 c    7.8
 b    6.4
 a    2.5
 f    0.0
 a    2.5
 dtype: float64)

In [95]:
print(df1)
df2 = df1.reindex(["B", "c", "gg", "GG", "aa", "b", "gg", "a"], method="bfill")
df2

   v1  v2  v3  v4    v5
a  10  25  32  42   NaN
b  85  75  96  45  10.0
c  68  78  94  83   NaN


v1    v2    v3    v4    v5
B   10.0  25.0  32.0  42.0   NaN
c   68.0  78.0  94.0  83.0   NaN
gg   NaN   NaN   NaN   NaN   NaN
GG  10.0  25.0  32.0  42.0   NaN
aa  85.0  75.0  96.0  45.0  10.0
b   85.0  75.0  96.0  45.0  10.0
gg   NaN   NaN   NaN   NaN   NaN
a   10.0  25.0  32.0  42.0   NaN

In [96]:
x = np.random.rand(100)
gender = np.where(x > 0.5, "M", "F")
height = np.rint(np.random.normal(loc=175, scale=6, size=100))
weight = np.rint(np.random.normal(loc=68, scale=3, size=100))
s1 = Series(gender)
s2 = Series(height, dtype=int)
s3 = Series(weight, dtype=int)
df = DataFrame({"gender" : s1, "height" : s2, "weight" : s3})
np.random.seed(1234)
rand_num = np.random.rand(100)
select = rand_num < 0.9
np.sum(select)
train_df = df[select]
test_df = df[~select]
male_170_greater = df[(df.gender == "M") & (df.height >= 170)]


In [130]:
s1 = Series([2.5, 7.6, 9.1], index=["c1", "c2", "c3"])
s2 = Series([3.1, 2.8, 7.5], index=["c1", "c2", "c3"])
data = {"att" : [3, 4, 1, 2], "hw" : [5, 3, 4, 1],"mid" : [15, 10, 12, 16], "fin" : [15, 10, 9, 10]}
df = DataFrame(data, index=["st1", "st2", "st3", "st4"])
print(s1)
print(s2)
print(df)
print(np.exp(s1))
print(np.minimum(s1,s2))
print(np.log(df))

c1    2.5
c2    7.6
c3    9.1
dtype: float64
c1    3.1
c2    2.8
c3    7.5
dtype: float64
     att  hw  mid  fin
st1    3   5   15   15
st2    4   3   10   10
st3    1   4   12    9
st4    2   1   16   10
c1      12.182494
c2    1998.195895
c3    8955.292703
dtype: float64
c1    2.5
c2    2.8
c3    7.5
dtype: float64
          att        hw       mid       fin
st1  1.098612  1.609438  2.708050  2.708050
st2  1.386294  1.098612  2.302585  2.302585
st3  0.000000  1.386294  2.484907  2.197225
st4  0.693147  0.000000  2.772589  2.302585


In [98]:
f = lambda x : x.max() - x.min()
print(df.apply(f))
print(df.apply(f, axis=1))

att    3
hw     4
mid    6
fin    6
dtype: int64
st1    12
st2    12
st3    11
st4    15
dtype: int64


In [105]:
def f(x):
    return Series([x.min(), x.max(), x.max() - x.min()], index=("최소", "최대", "범위"))
df_f = df.apply(f)
df_f

att  hw  mid  fin
최소    1   1   10    9
최대    4   5   16   15
범위    3   4    6    6

In [126]:
def f(x):
    fa =1
    for i in range(1, (x + 1)):
        fa *= i
    return fa
df.applymap(f)
df.applymap(np.math.factorial)

att   hw             mid            fin
st1    6  120   1307674368000  1307674368000
st2   24    6         3628800  1307674368000
st3    1   24       479001600         362880
st4    2    1  20922789888000        3628800

In [111]:
s = Series([2.5, np.inf, 3.1, np.nan, 7.5], index=["c5", "c3", "c2", "c3", "c1"])
df3 = DataFrame(data, index=["st3", "st2", "st4", "st1"])
s, df3

(c5    2.5
 c3    inf
 c2    3.1
 c3    NaN
 c1    7.5
 dtype: float64,      att  hw  mid  fin
 st3    3   5   15   12
 st2    4   3   10   15
 st4    1   4   12    9
 st1    2   1   16   10)

In [112]:
print(s.sort_index(ascending=False))
print(s.sort_values(ascending=False))
print(s.sort_values())

c5    2.5
c3    inf
c3    NaN
c2    3.1
c1    7.5
dtype: float64
c3    inf
c1    7.5
c2    3.1
c5    2.5
c3    NaN
dtype: float64
c5    2.5
c2    3.1
c1    7.5
c3    inf
c3    NaN
dtype: float64


In [116]:
df.sort_index(ascending=False), df.sort_index(axis=1)

(     att  hw  mid  fin
 st4    2   1   16   10
 st3    1   4   12    9
 st2    4   3   10   15
 st1    3   5   15   12,      att  fin  hw  mid
 st1    3   12   5   15
 st2    4   15   3   10
 st3    1    9   4   12
 st4    2   10   1   16)

In [138]:
df.sort_values(by="fin"), df.sort_values(by=["fin", "mid"])

(     att  hw  mid  fin
 st2    1   4   12    9
 st1    4   3   10   10
 st1    2   1   16   10
 st3    3   5   15   15,      att  hw  mid  fin
 st2    1   4   12    9
 st1    4   3   10   10
 st1    2   1   16   10
 st3    3   5   15   15)

In [141]:
print(s.rank(ascending=False))
print(df.rank(method="max"))
print(df.rank(method="average", axis=1))
print(df.rank(method="dense"))

c5    4.0
c3    1.0
c2    3.0
c3    NaN
c1    2.0
dtype: float64
     att   hw  mid  fin
st3  3.0  4.0  3.0  4.0
st1  4.0  2.0  1.0  3.0
st2  1.0  3.0  2.0  1.0
st1  2.0  1.0  4.0  3.0
     att   hw  mid  fin
st3  1.0  2.0  3.5  3.5
st1  2.0  1.0  3.5  3.5
st2  1.0  2.0  4.0  3.0
st1  2.0  1.0  4.0  3.0
     att   hw  mid  fin
st3  3.0  4.0  3.0  3.0
st1  4.0  2.0  1.0  2.0
st2  1.0  3.0  2.0  1.0
st1  2.0  1.0  4.0  2.0


In [131]:
s2 = Series([2.5, np.inf, 3.1, np.nan, 7.5], index=["c2", "c4", "c2", "c3", "c1"])
df = DataFrame(data, index=["st3","st1" ,"st2" ,"st1"])
s2, df

(c2    2.5
 c4    inf
 c2    3.1
 c3    NaN
 c1    7.5
 dtype: float64,      att  hw  mid  fin
 st3    3   5   15   15
 st1    4   3   10   10
 st2    1   4   12    9
 st1    2   1   16   10)

In [189]:
print(s2.index.is_unique)
print(s2[["c2"]])
print(df.index.is_unique)
print(df.loc["st1"])

False
c2    2.5
c2    3.1
dtype: float64
False
                                             att  hw  mid  fin
st1  <function to_numeric at 0x000001F6F3F11C80>   3   10   10
st1  <function to_numeric at 0x000001F6F3F11C80>   1   16   10


In [145]:
print(s.mean())
print(s.mean(skipna=False))
print(df.mean())
df.mean(skipna=False)

inf
nan
att     2.50
hw      3.25
mid    13.25
fin    11.00
dtype: float64


att     2.50
hw      3.25
mid    13.25
fin    11.00
dtype: float64

In [170]:
df.sum(axis=1)
df.cumsum(axis=1, skipna=False)
df.quantile(q=[0.1, 0.5])

att   hw   mid   fin
0.1  2.0  1.6  10.6   9.3
0.5  2.5  3.5  13.5  10.0

In [151]:
print(df.std())
print(df.cummin())
print(df.diff())

att    1.290994
hw     1.707825
mid    2.753785
fin    2.708013
dtype: float64
     att  hw  mid  fin
st3    3   5   15   15
st1    3   3   10   10
st2    1   3   10    9
st1    1   1   10    9
     att   hw  mid  fin
st3  NaN  NaN  NaN  NaN
st1  1.0 -2.0 -5.0 -5.0
st2 -3.0  1.0  2.0 -1.0
st1  1.0 -3.0  4.0  1.0


In [155]:
print(df.describe())
s4 = Series(["A", "B", "A", "C", "B", "B",np.nan ], index=["case" + str(x) for x in range(1,8)])
print(s4.describe())

            att        hw        mid        fin
count  4.000000  4.000000   4.000000   4.000000
mean   2.500000  3.250000  13.250000  11.000000
std    1.290994  1.707825   2.753785   2.708013
min    1.000000  1.000000  10.000000   9.000000
25%    1.750000  2.500000  11.500000   9.750000
50%    2.500000  3.500000  13.500000  10.000000
75%    3.250000  4.250000  15.250000  11.250000
max    4.000000  5.000000  16.000000  15.000000
count     6
unique    3
top       B
freq      3
dtype: object
