# 단어 표현

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


## 정수 인코딩

In [ ]:
text="A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [2]:
import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')


text = sent_tokenize(text)
print(text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [5]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter
nltk.download('stopwords')


vocab = Counter()

sentences = []
stop_words = set(stopwords.words("english"))

for i in text:
    sentence = word_tokenize(i)
    result = []

    for word in sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2:
                result.append(word)
                vocab[word] = vocab[word] + 1
    sentences.append(result)

print(sentences)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [6]:
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [1]:
vocab_sorted = sorted(vocab.items(), key=lambda x:x[1], reverse=True)
print(vocab_sorted)

NameError: name 'vocab' is not defined

In [8]:
word_to_index = {}
i = 0
for (word, frequency) in vocab_sorted:
    if frequency > 1:
        i += 1
        word_to_index[word] = i
    
print(word_to_index)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


## 케라스 전처리

In [9]:
from keras.preprocessing.text import Tokenizer
text=["A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."]
t = Tokenizer()
t.fit_on_texts(text)

Using TensorFlow backend.


In [10]:
print(t.word_index)

{'a': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'his': 5, 'is': 6, 'kept': 7, 'person': 8, 'the': 9, 'he': 10, 'word': 11, 'keeping': 12, 'good': 13, 'knew': 14, 'but': 15, 'and': 16, 'such': 17, 'to': 18, 'himself': 19, 'was': 20, 'driving': 21, 'crazy': 22, 'went': 23, 'up': 24, 'mountain': 25}


In [11]:
print(t.word_counts)

OrderedDict([('a', 8), ('barber', 8), ('is', 4), ('person', 3), ('good', 1), ('huge', 5), ('he', 2), ('knew', 1), ('secret', 6), ('the', 3), ('kept', 4), ('his', 5), ('word', 2), ('but', 1), ('keeping', 2), ('and', 1), ('such', 1), ('to', 1), ('himself', 1), ('was', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('up', 1), ('mountain', 1)])


In [13]:
print(t.texts_to_sequences(text))

[[1, 2, 6, 1, 8, 1, 2, 6, 13, 8, 1, 2, 6, 4, 8, 10, 14, 1, 3, 9, 3, 10, 7, 6, 4, 3, 4, 3, 5, 2, 7, 5, 11, 1, 2, 7, 5, 11, 5, 2, 7, 5, 3, 15, 12, 16, 12, 17, 1, 4, 3, 18, 19, 20, 21, 9, 2, 22, 9, 2, 23, 24, 1, 4, 25]]


In [15]:
words_frequency = [w for w,c in t.word_counts.items() if c < 2]

for w in words_frequency:
    del t.word_index[w]
    del t.word_counts[w]

print(t.texts_to_sequences(text))
print(t.word_index)

[[1, 2, 6, 1, 8, 1, 2, 6, 8, 1, 2, 6, 4, 8, 10, 1, 3, 9, 3, 10, 7, 6, 4, 3, 4, 3, 5, 2, 7, 5, 11, 1, 2, 7, 5, 11, 5, 2, 7, 5, 3, 12, 12, 1, 4, 3, 9, 2, 9, 2, 1, 4]]
{'a': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'his': 5, 'is': 6, 'kept': 7, 'person': 8, 'the': 9, 'he': 10, 'word': 11, 'keeping': 12}


## bag of words(bow)

In [17]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 3.4MB/s 
     |████████████████████████████████| 2.7MB 40.3MB/s 


In [18]:
from konlpy.tag import Okt
import re
okt = Okt()


token = re.sub("(\.)", "", "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")
token = okt.morphs(token)

word2index = {}
bow = []
for voca in token:
    if voca not in word2index.keys():
        word2index[voca] = len(word2index)
        bow.insert(len(word2index) - 1, 1)
    else:
        index = word2index.get(voca)
        bow[index] = bow[index] + 1

print(word2index)

/usr/local/lib/python3.6/dist-packages/jpype/_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}


In [19]:
bow

[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]

In [20]:
from sklearn.feature_extraction.text import CountVectorizer


corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [21]:
from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [22]:
from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
from nltk.corpus import stopwords
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [24]:
type(sw)

list

## TDM

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
          "you know I want your love",
          "I like you",
          "what should I do"
]
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)


[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
path = "/content/drive/My Drive/lecture/l_d/p8/폭염 (1990.01.01-2018.07.31)_5.csv"

In [31]:
import pandas as pd


df = pd.read_csv(path, sep=",", quotechar='"', error_bad_lines=False, encoding="EUC-KR")

b'Skipping line 15: expected 18 fields, saw 19\nSkipping line 71: expected 18 fields, saw 19\nSkipping line 74: expected 18 fields, saw 19\nSkipping line 79: expected 18 fields, saw 19\nSkipping line 94: expected 18 fields, saw 19\nSkipping line 110: expected 18 fields, saw 19\nSkipping line 118: expected 18 fields, saw 19\nSkipping line 120: expected 18 fields, saw 19\nSkipping line 130: expected 18 fields, saw 19\nSkipping line 137: expected 18 fields, saw 19\nSkipping line 159: expected 18 fields, saw 19\nSkipping line 168: expected 18 fields, saw 19\nSkipping line 174: expected 18 fields, saw 19\nSkipping line 190: expected 18 fields, saw 20\nSkipping line 194: expected 18 fields, saw 19\nSkipping line 210: expected 18 fields, saw 21\nSkipping line 214: expected 18 fields, saw 20\nSkipping line 222: expected 18 fields, saw 19\nSkipping line 237: expected 18 fields, saw 19\nSkipping line 245: expected 18 fields, saw 20\nSkipping line 260: expected 18 fields, saw 19\nSkipping line 26

In [32]:
df.head()

주소  ...                                               원본주소
0  http://www.bigkinds.or.kr/news/newsDetailView....  ...  http://biz.heraldcorp.com/view.php?ud=20180724...
1  http://www.bigkinds.or.kr/news/newsDetailView....  ...  http://biz.heraldcorp.com/view.php?ud=20180724...
2  http://www.bigkinds.or.kr/news/newsDetailView....  ...         http://www.sedaily.com/NewsView/1S27K8I4H4
3  http://www.bigkinds.or.kr/news/newsDetailView....  ...         http://www.sedaily.com/NewsView/1S27KI9O3X
4  http://www.bigkinds.or.kr/news/newsDetailView....  ...      http://www.fnnews.com/news/201807231714237258

[5 rows x 18 columns]

In [33]:
df.shape

(4924, 18)

In [34]:
df.columns

Index(['주소', '일자', '언론사', '기고자', '제목', '통합 분류1', '통합 분류2', '통합 분류3',
       '사건/사고 분류1', '사건/사고 분류2', '사건/사고 분류3', '개체명(인물)', '개체명(지역)',
       '개체명(기업/기관)', '키워드', '특성추출', '본문', '원본주소'],
      dtype='object')

In [35]:
df["본문"].head()

0    23일 경북 경산 39.9도까지 치솟아 1942년 8월1일 대구 40.0도 기..열...
1    롭스, 네일·염모제 매출 각각 52%·31% ↑ “아무리 더워도 아름다움 양보 못해...
2    중국의 창성바이오가 가짜백신으로 상장폐지 위기. 국내 제약바이오주들도 덩달아 급락....
3    중국의 창성바이오가 가짜백신으로 상장폐지 위기. 국내 제약바이오주들도 덩달아 급락....
4    OECD 주요국과 역행.. 탈원전이 상황 악화시켜       지난해 우리나라 이산화...
Name: 본문, dtype: object

In [36]:
from konlpy.tag import Komoran


tagger = Komoran()
tagger.nouns("아침에 해를 보며 버스를 탔다")

['아침', '해', '버스']

In [ ]:
import re


def get_nouns(text):
    nouns = tagger.nouns(text)
    nouns = [word for word in nouns if len(word) > 1]
    nouns = [word for word in nouns if not re.match(r"\d+", word)]
    return nouns

In [38]:
get_nouns("아침에 해를 보며 버스를 탔다")

['아침', '버스']

In [41]:
from sklearn.feature_extraction.text import CountVectorizer


cv = CountVectorizer(max_features=1000, tokenizer=get_nouns)
tdm = cv.fit_transform(df["본문"])
cv.get_feature_names()[:10]

['.co', '.com', '.kr', '가격', '가구', '가동', '가량', '가마솥', '가뭄', '가운데']

In [ ]:
from sklearn.externals import joblib


with open("hot_news.pkl", "wb") as f:
    joblib.dump({"vectorizer":cv, "tdm":tdm}, f)

In [ ]:
with open("hot_news.pkl", "rb") as f:
    data = joblib.load(f)

In [ ]:
cv_2 = data["vectorizer"]

In [ ]:
tdm_2 = data["tdm"]

In [ ]:
count = tdm_2.sum(axis=0)

In [67]:
import pandas as pd


word_count = pd.DataFrame({
    "단어" : cv_2.get_feature_names(),
    "빈도" : count.flat
})

/usr/local/lib/python3.6/dist-packages/pandas/core/dtypes/dtypes.py:458: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if string == 'category':


In [68]:
word_count.tail()

단어   빈도
995   훈련   35
996   휴가  123
997  휴가철  137
998   휴식  125
999   휴일   36

In [69]:
sorted_df = word_count.sort_values("빈도", ascending=False)
sorted_df.head()

단어     빈도
921  폭염  10678
931  피해   1341
822  지역   1225
162  기자   1165
65   계속   1077

## TF-IDF

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


## 아마존 리뷰데이터 TDM, TF-IDF

In [3]:
from urllib.request import urlretrieve


urlretrieve("http://doc.mindscale.kr/km/unstructured/review.gz", "review.gz")

('review.gz', <http.client.HTTPMessage at 0x7f567b7eeac8>)

In [ ]:
import pandas as pd


df = pd.read_csv('review.gz')

In [15]:
df.head()

reviewText  overall
0  They look good and stick good! I just don't li...        4
1  These stickers work like the review says they ...        5
2  These are awesome and make my phone look so st...        5
3  Item arrived in great time and was in perfect ...        4
4  awesome! stays on, and looks great. can be use...        5

In [ ]:
df = df.dropna()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


cv = CountVectorizer(max_features=1000, stop_words='english')
tdm = cv.fit_transform(df['reviewText'])

In [ ]:
words = cv.get_feature_names()
count = tdm.sum(axis=0)

In [ ]:
word_count = list(zip(words, count.flat))

In [20]:
word_count

[('10', 7810),
 ('100', 4240),
 ('12', 2490),
 ('15', 2309),
 ('1a', 3029),
 ('20', 3685),
 ('25', 1773),
 ('30', 4659),
 ('34', 16953),
 ('3g', 2332),
 ('40', 1453),
 ('4g', 3884),
 ('4s', 5421),
 ('50', 2622),
 ('5s', 3639),
 ('8217', 4338),
 ('ability', 1922),
 ('able', 11460),
 ('absolutely', 3543),
 ('ac', 2722),
 ('access', 3859),
 ('accessories', 1624),
 ('actual', 2084),
 ('actually', 10653),
 ('adapter', 6805),
 ('adapters', 1664),
 ('add', 5374),
 ('added', 2973),
 ('addition', 1851),
 ('additional', 2032),
 ('adds', 2949),
 ('adjust', 1711),
 ('advertised', 2686),
 ('ago', 2762),
 ('air', 3562),
 ('allow', 2822),
 ('allows', 4156),
 ('amazing', 4316),
 ('amazon', 10296),
 ('amp', 2272),
 ('amps', 1494),
 ('android', 8018),
 ('angle', 1654),
 ('anker', 3457),
 ('annoying', 2886),
 ('answer', 2404),
 ('anti', 1746),
 ('anymore', 1484),
 ('apart', 2755),
 ('app', 5158),
 ('appears', 1937),
 ('apple', 10633),
 ('application', 2406),
 ('apply', 3618),
 ('apps', 4861),
 ('area', 3

In [ ]:
import operator


word_order = sorted(
    word_count,
    key=operator.itemgetter(1), # 0이면 단어 순, 1이면 빈도 순
    reverse=True)               # 내림차순(역순)으로 정렬한다

In [22]:
word_order[:10]

[('phone', 181717),
 ('case', 150035),
 ('like', 74073),
 ('great', 68898),
 ('use', 63229),
 ('screen', 62373),
 ('just', 61980),
 ('good', 60355),
 ('battery', 59361),
 ('iphone', 49758)]

In [23]:
df.shape

(194340, 2)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfv = TfidfVectorizer().fit(df["reviewText"].tolist())

In [25]:
print(tfidfv.transform(df["reviewText"][:10000]).toarray())
print(tfidfv.vocabulary_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
{'they': 77004, 'look': 46639, 'good': 35530, 'and': 9240, 'stick': 72953, 'just': 43857, 'don': 26912, 'like': 45927, 'the': 76274, 'rounded': 65967, 'shape': 68457, 'because': 13265, 'was': 83530, 'always': 8840, 'bumping': 16087, 'it': 42844, 'siri': 69545, 'kept': 44102, 'popping': 59045, 'up': 81243, 'irritating': 42602, 'won': 85176, 'buy': 16398, 'product': 60527, 'this': 77199, 'again': 8056, 'these': 76851, 'stickers': 72961, 'work': 85279, 'review': 65173, 'says': 66904, 'do': 26737, 'on': 54028, 'great': 36080, 'stay': 72794, 'phone': 57475, 'are': 10371, 'super': 74200, 'stylish': 73686, 'can': 17047, 'share': 68473, 'them': 76584, 'with': 84947, 'my': 51151, 'sister': 69566, 'awesome': 11611, 'make': 47655, 'so': 70830, 'have': 37491, 'only': 54215, 'used': 81645, 'one': 54073, 'far': 31484, 'had': 36848, 'for': 33222, 

In [ ]:
df_2 = pd.DataFrame(tdm.toarray())

In [ ]:
import numpy as np


df_3 = df_2.apply(lambda x:x*np.log(df.shape[0]/ (x + 1)))

In [32]:
df_3.head()

0    1    2    3    4    5    6    ...  993  994  995  996        997  998  999
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   0.000000  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   0.000000  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  22.157504  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   0.000000  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   0.000000  0.0  0.0

[5 rows x 1000 columns]

In [34]:
df_3.sum(axis=1)

0         158.346252
1         114.842173
2         136.999677
3         216.578268
4         137.810608
5         114.842173
6         126.326390
7          80.389521
8         250.219990
9         182.936547
10         91.873738
11        301.896472
12        215.309757
13        767.312245
14        157.888670
15         68.905304
16        181.314686
17        125.515460
18        406.840149
19        126.326390
20        125.515460
21         79.578591
22        103.357956
23        102.547025
24         91.873738
25        125.515460
26         91.873738
27        294.077418
28         22.968435
29         91.873738
             ...    
194310    126.326390
194311     22.968435
194312     91.873738
194313     68.905304
194314     34.452652
194315     79.578591
194316    114.031243
194317     57.421087
194318    317.045852
194319    296.156859
194320     68.905304
194321    216.578268
194322     57.421087
194323    225.983044
194324    218.200129
194325     45.936869
194326    159

## 단어 유사도 by using word2vec

In [ ]:
import re
from lxml import etree
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize


path = "/content/drive/My Drive/lecture/l_d/p8/ted_en-20160408.xml"
targetXML = open(path, "r", encoding="UTF8")
target_text = etree.parse(targetXML)
parse_text = "\n".join(target_text.xpath("//content/text()"))

In [3]:
parse_text

Output hidden; open in https://colab.research.google.com to view.

In [5]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
content_text = re.sub(r"\([^)]*\)", "", parse_text)
sent_text = sent_tokenize(content_text)

In [ ]:
normalized_text = []
for string in sent_text:
     tokens = re.sub(r"[^a-z0-9]+", " ", string.lower())
     normalized_text.append(tokens)

In [ ]:
result=[]
result=[word_tokenize(sentence) for sentence in normalized_text]

In [9]:
print(result[:10])

[['here', 'are', 'two', 'reasons', 'companies', 'fail', 'they', 'only', 'do', 'more', 'of', 'the', 'same', 'or', 'they', 'only', 'do', 'what', 's', 'new'], ['to', 'me', 'the', 'real', 'real', 'solution', 'to', 'quality', 'growth', 'is', 'figuring', 'out', 'the', 'balance', 'between', 'two', 'activities', 'exploration', 'and', 'exploitation'], ['both', 'are', 'necessary', 'but', 'it', 'can', 'be', 'too', 'much', 'of', 'a', 'good', 'thing'], ['consider', 'facit'], ['i', 'm', 'actually', 'old', 'enough', 'to', 'remember', 'them'], ['facit', 'was', 'a', 'fantastic', 'company'], ['they', 'were', 'born', 'deep', 'in', 'the', 'swedish', 'forest', 'and', 'they', 'made', 'the', 'best', 'mechanical', 'calculators', 'in', 'the', 'world'], ['everybody', 'used', 'them'], ['and', 'what', 'did', 'facit', 'do', 'when', 'the', 'electronic', 'calculator', 'came', 'along'], ['they', 'continued', 'doing', 'exactly', 'the', 'same']]


In [ ]:
from gensim.models import Word2Vec


model = Word2Vec(sentences=result, size=100, window=5, min_count=5, workers=4, sg=0)

In [12]:
a = model.wv.most_similar("man")
print(a)

[('woman', 0.859825611114502), ('guy', 0.7987077236175537), ('lady', 0.7879853248596191), ('boy', 0.7511061429977417), ('girl', 0.7502450942993164), ('soldier', 0.7316014766693115), ('gentleman', 0.7313390374183655), ('kid', 0.7080129384994507), ('poet', 0.6769150495529175), ('surgeon', 0.6733406186103821)]


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [ ]:
model_2 = Word2Vec(sentences=result, size=200, window=10, min_count=5, workers=10, sg=1)

In [14]:
b = model.wv.most_similar("man")

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [15]:
b

[('woman', 0.859825611114502),
 ('guy', 0.7987077236175537),
 ('lady', 0.7879853248596191),
 ('boy', 0.7511061429977417),
 ('girl', 0.7502450942993164),
 ('soldier', 0.7316014766693115),
 ('gentleman', 0.7313390374183655),
 ('kid', 0.7080129384994507),
 ('poet', 0.6769150495529175),
 ('surgeon', 0.6733406186103821)]

In [17]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 6.2MB/s 
     |████████████████████████████████| 2.7MB 38.2MB/s 


In [ ]:
import nltk
from konlpy.corpus import kobill


doc_ko = kobill.open("1809894.txt")


In [ ]:
from konlpy.tag import Okt


okt = Okt()

In [ ]:
n = 0
result = []

while True:
    line = doc_ko.readline()
    if not line:
        break
    n += 1
    if n % 5000 == 0:
        print(f"{n}번째")
    tokenlist = okt.pos(line, stem=True, norm=True)
    temp = []
    for word in tokenlist:
        if word[1] in ["Noun"]:
            temp.append((word[0]))
    
    if temp:
        result.append(temp)
    
doc_ko.close()

In [29]:
len(result)

49

In [ ]:
from gensim.models import Word2Vec


model = Word2Vec(result, size=100, window=5, min_count=5, workers=5, sg=0)

In [32]:
a = model.wv.most_similar("학위")
a

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('및', 0.1739576905965805),
 ('연한', 0.0628741979598999),
 ('정', 0.03613690286874771),
 ('간호', -0.02710808254778385),
 ('안', -0.0398770272731781),
 ('제', -0.042407386004924774),
 ('수업', -0.046072959899902344),
 ('관', -0.0902535617351532)]

## 학습된 모델 사용

In [34]:
import gensim

path = "/content/drive/My Drive/lecture/l_d/p8/"
model = gensim.models.Word2Vec.load(path + "ko.bin")
a = model.wv.most_similar("강아지")
a

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('고양이', 0.7290452718734741),
 ('거위', 0.7185635566711426),
 ('토끼', 0.7056223154067993),
 ('멧돼지', 0.6950401067733765),
 ('엄마', 0.6934334635734558),
 ('난쟁이', 0.6806551218032837),
 ('한마리', 0.6770296096801758),
 ('아가씨', 0.6750352382659912),
 ('아빠', 0.6729634404182434),
 ('목걸이', 0.6512460708618164)]

In [ ]:
a = model

## 네이버 영화리뷰 word2vec만들기

In [ ]:
import pandas as pd
import numpy as np

path = "/content/drive/My Drive/lecture/l_d/p8/"

ntrain = 150000

data = pd.read_csv(path + "ratings.txt", sep='\t', quoting=3)
# data = pd.DataFrame(np.random.permutation(data))
# trn, tst = data[:ntrain], data[ntrain:]

# header = 'id document label'.split()
# trn.to_csv(path + 'ratings_train.txt', sep='\t', index=False, header=header)
# tst.to_csv(path + 'ratings_test.txt', sep='\t', index=False, header=header)

In [57]:
data.head()

id                                           document  label
0   8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
1   8132799  디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산...      1
2   4655635               폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.      1
3   9251303  와.. 연기가 진짜 개쩔구나.. 지루할거라고 생각했는데 몰입해서 봤다.. 그래 이런...      1
4  10067386                        안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화.      1

In [ ]:
from konlpy.tag import Okt


okt = Okt()

result = []
doc_list = data["document"].tolist()

In [60]:
len(doc_list)

200000

In [ ]:
from tqdm import tqdm


for doc in tqdm(doc_list):
    malist = okt.pos(doc, norm=True, stem=True)
    r=[]
    for word in malist:
        if not word[1] in ["Josa", "Eomi", "Punctuation"]:
            r.append(word[0])
            rl = (" ".join(r)).strip()
            result.append(rl)

In [42]:
import csv

f = open(path + "ratings.txt",'r',encoding = 'utf-8')
rdr = csv.reader(f, delimiter = '\t')
rdw = list(rdr)

print(rdw[:3])

f.close()

[['id', 'document', 'label'], ['8112052', '어릴때보고 지금다시봐도 재밌어요ㅋㅋ', '1'], ['8132799', '디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업이 부러웠는데. 사실 우리나라에서도 그 어려운시절에 끝까지 열정을 지킨 노라노 같은 전통이있어 저와 같은 사람들이 꿈을 꾸고 이뤄나갈 수 있다는 것에 감사합니다.', '1']]


In [ ]:
from konlpy.tag import Okt


okt = Okt()

result = []
for line in rdw:
    malist = okt.pos(line[1], norm=True, stem=True)
    r = []
    for word in malist:
        if not word[1] in ["Josa","Eomi","Punctuation"]:
            r.append(word[0])
            rl = (" ".join(r)).strip()
            result.append(rl)

In [ ]:
with open(path + "naverMovie.nlp", "w", encoding="utf-8") as f:
    f.write("\n".join(result))

In [70]:
 from gensim.models import word2vec
 
 
 wData = word2vec.LineSentence(path + "naverMovie.nlp")
 wModel =word2vec.Word2Vec(wData, size=200, window=10, hs=1, min_count=2, sg=1)
 wModel.save("NaverMovie.model")
 print("Word2Vec Modeling finished")

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


Word2Vec Modeling finished


In [ ]:
from gensim.models import word2vec

model = word2vec.Word2Vec.load("NaverMovie.model")

print(model.most_similar(positive=["재미"]))

print(model.most_similar(positive=["최고"]))